name: Setup
description: Setup environment

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0

    - run: echo "dir=$(npm config get cache)" >> "$GITHUB_OUTPUT"
      id: cache
      shell: bash

    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
      shell: bash
